#!/bin/bash
set -e

# This file links all the configuration files and directories to the known places. If a destination already exists, a backup is created.

# Symbolic links must be linked to absolute paths.
# All dotfiles should be linked from the current working directory.
# We still need to add some validation that we current are in the dotfiles directory.
dotfiles="$(pwd)"

# Installs the file or directory with a symbolic link.
# Two arguments are required:
# $1: Name of the file to link, eq. gitconfig
# $1: Destination path, eq. $HOME/.gitconfig
function install() {
    echo "Installing $1 to $2"

    if [ -f "$2" ] ; then
        echo "Destination $2 already exists and will be overwritten."
        rm -f "$2"
    elif [ -d "$2" ] ; then
        echo "Destination $2 already exists and will be overwritten."
    	rm -rf "$2"
    fi

    # symbolic: make symbolic links instead of hard links
    ln --symbolic "$dotfiles/$1" "$2"
}

install "gitconfig" "$HOME/.gitconfig"
install "fonts" "$HOME/.fonts"
install "profile" "$HOME/.profile"
install "zshrc" "$HOME/.zshrc"
install "Sublime-User" "$HOME/.config/sublime-text-3/Packages/User"
install "awesome" "$HOME/.config/awesome"
install "vimperatorrc" "$HOME/.vimperatorrc"
install "vimrc.local" "$HOME/.vimrc.local"
install "vimrc.before.local" "$HOME/.vimrc.before.local"
install "vimrc.bundles.local" "$HOME/.vimrc.bundles.local"
install "xprofile" "$HOME/.xprofile"

sudo cp -f "$dotfiles/awesome.session" "/usr/share/gnome-session/sessions/awesome.session"
sudo cp -f "$dotfiles/awesome.desktop" "/usr/share/applications/awesome.desktop"
sudo cp -f "$dotfiles/awesome-gnome.desktop" "/usr/share/xsessions/awesome-gnome.desktop"
