#!/bin/bash

##
#  MacBook Fan Control Daemon
#
#  This software controls the fan in the MacBook
##
if ! hash mbpfan 2>/dev/null ; then
    echo "Installing MacBook Fan Control Daemon"
    sudo apt-get install build-essential -y -qq
    git clone https://github.com/dgraziotin/Fan-Control-Daemon.git $HOME/.Fan-Control-Daemon
    cd $HOME/.Fan-Control-Daemon
    make
    sudo make install
    sudo cp mbpfan.upstart /etc/init/mbpfan.conf
    sudo start mbpfan
else
    echo "Skipping MacBook Fan Control Deamon... mbpfan already exists"
fi

##
#  rbenv and ruby-build
##
if ! hash rbenv 2>/dev/null ; then
    echo "Installing rbenv"
    git clone https://github.com/sstephenson/rbenv.git $HOME/.rbenv
    git clone https://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build

    # Packages required by ruby
    sudo apt-get install libssl-dev build-essential -y -qq
else
    echo "Skipping rbenv... rbenv already exists"
fi

##
#  The Ultimate Vim Distribution
##
if [ ! -d "$HOME/.spf13-vim-3" ] ; then
    echo "Installing The Ultimate Vim Distribution"
    sudo apt-get install vim -y -qq
    curl http://j.mp/spf13-vim3 -L -o - | sh
fi

##
#  Autojump
##
if ! hash autojump 2>/dev/null ; then
    echo "Installing autojump"
    sudo apt-get install autojump -y -qq
fi

##
#  Go 1.1.2
##
if ! hash go 2>/dev/null ; then
    echo "Installing Google's Go"
    wget https://go.googlecode.com/files/go1.1.2.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.1.2.linux-amd64.tar.gz
    rm go1.1.2.linux-amd64.tar.gz

    # Create workspace directories
    mkdir -p "$HOME/go/"{src,pkg,bin}
fi

##
#  HipChat
##
if ! hash hipchat 2>/dev/null ; then
    echo "Installing hipchat"
    echo "deb http://downloads.hipchat.com/linux/apt stable main" | \
        sudo tee "/etc/apt/sources.list.d/atlassian-hipchat.list"

    wget -O - https://www.hipchat.com/keys/hipchat-linux.key | \
        sudo apt-key add -
    sudo apt-get update -y -qq
    sudo apt-get install hipchat -y -qq
fi

##
#  Docker
##
if ! hash docker 2>/dev/null ; then
    echo "Install docker"

    # Enable AUFS filesystem support
    sudo apt-get install linux-image-extra-`uname -r` -y -qq
    sudo sh -c "curl https://get.docker.io/gpg | apt-key add -"
    sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
    sudo apt-get update -y -qq
    sudo apt-get install lxc-docker -y -qq
fi

##
#  SimpleScreenRecorder
#  http://www.maartenbaert.be/simplescreenrecorder/#download
##
if ! hash simplescreenrecorder 2>/dev/null ; then
    echo "Install SimpleScreenRecorder"
    sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder
    sudo apt-get update -q
    sudo apt-get install simplescreenrecorder -y -q
fi

if ! hash bzr 2>/dev/null ; then
    echo "Installing bzr"
    sudo apt-get install bzr -y
fi

if ! hash hg 2>/dev/null ; then
    echo "Installing mercurial"
    sudo apt-get install mercurial -y
