#! /bin/zsh
# Trap output to also write to log
#LOG_FILE="$HOME/bspwm.log"
#exec 3>&1 1>>${LOG_FILE} 2>&1

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# Colors
bspc config normal_border_color   "#626483"
#bspc config normal_border_color   "#b45bcf"
#bspc config focused_border_color  "#b45bcf"
bspc config focused_border_color  "#ebff87"
bspc config active_border_color   "#b45bcf"
bspc config presel_feedback_color "#62d6e8"

# Windows
bspc config border_width          2
bspc config top_padding           0
bspc config window_gap            18
bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config single_monocle        false
bspc config focus_follows_pointer false
bspc config click_to_focus        button1
bspc config pointer_modifier      mod4

bspc config ignore_ewmh_focus true

source $HOME/.profile

logins=($(find $DOTFILES -executable -type f -name login))
for login in $logins; do
  echo "login script: $login"
  source $login
done
