#!/bin/sh
keyfile="$HOME/.ssh/wercker-us-west1.pem"
if [ ! -f $keyfile ] ; then
    echo "Missing $keyfile key file in .ssh folder"
    exit 1
fi

ssh -i "$keyfile" mongodb-03-app.wercker.com -l ubuntu
