#!/bin/zsh
local IM_DESKTOP="^10"

function im::open() {
  local command=${1:?"The command must be specified"}
  local wm_class=${2:?"The WM_CLASS must be specified"}

  echo "opening: $command"

  bspc rule -a "$wm_class" desktop="^10" follow=off focus=off
  $command &
}

# slack
im::open "slack" "Slack"

# signal
im::open "signal-desktop" "Signal"
#
# whatsapp
im::open "whatsapp-nativefier" "whatsapp-nativefier-d40211"

# discord
im::open "discord" "Discord"

# teams
#im::open "teams" "Microsoft Teams - Preview"
