#!/bin/zsh

while true;
do
	HOST=$(curl ifconfig.me 2> /dev/null)
	if [ $? -ne 0 ]; then
		echo "# ifconfig.me failed"
		sleep 1
		continue
	fi

	if ! ping=$(ping -n -c 1 -W 1 $HOST); then
		echo "# ping failed"
		sleep 1
		continue
	fi

	rtt=$(echo "$ping" | sed -rn 's/.*time=([0-9]{1,})\.?[0-9]{0,} ms.*/\1/p')

	if [ "$rtt" -lt 25 ]; then
		echo " ${rtt} ms"
	elif [ "$rtt" -lt 51 ]; then
		# orange
		echo "%{F#f9dd04} ${rtt} ms%{F-}"
	else
		# red
		echo "%{F#d60606} ${rtt} ms%{F-}"
	fi
	sleep 0.5
done
