#!/bin/zsh
playerctl metadata -F --format "{{ title }} - {{ artist }}" | while read -r line; do
	s=$(playerctl status)
	if [ $? -ne 0 ]
	then
			echo "nothing is playing"
			exit 1
	fi


	case $s in
		Playing)
				echo " $(playerctl metadata --format "{{ title }} - {{ artist }}")"
				;;
		Paused)
				echo " $(playerctl metadata --format "{{ title }} - {{ artist }}")"
				;;
		*)
				echo " $(playerctl metadata --format "{{ title }} - {{ artist }}")"
				;;
	esac
done
