#!/bin/zsh
s=$(playerctl status)
if [ $? -ne 0 ]
then
    echo "nothing is playing"
    exit 1
fi


case $s in
  Playing)
      echo "  $(playerctl metadata artist) - $(playerctl metadata title)"
      ;;
  Paused)
      echo " $(playerctl metadata artist) - $(playerctl metadata title)"
      ;;
  *)
      echo " $(playerctl metadata artist) - $(playerctl metadata title)"
      ;;
esac
