#!/bin/bash

# needs jq, chwb, xprop
command -v jq >/dev/null 2>&1 || { echo >&2 "Command jq is required to run this script and is missing.  Aborting."; exit 1; }
command -v chwb >/dev/null 2>&1 || { echo >&2 "Command chwb (part of wmutils) is required to run this script and is missing.  Aborting."; exit 1; }
command -v xprop >/dev/null 2>&1 || { echo >&2 "Command xprop (part of wmutils) is required to run this script and is missing.  Aborting."; exit 1; }

declare -A profiles=(
  [born2code]='#bd93f9'
  [craftify]='#ff79c6'
  [deloitte]='#50FA7B'
  [deloitte-admin]='#ff5555'
)

bspc subscribe node_stack | while read -r action monitor_id desktop_id node_id; do
    echo action: $action
    echo monitor: $monitor_id
    echo desktop: $desktop_id
    echo node_id: $node_id

    className=$(bspc query -T -n $node_id | jq -r '.client.className')
    echo className: $className

    if [ "$className" != "qutebrowser" ]; then
      continue
    fi

    wm_name=$(xprop -id $node_id WM_NAME)

    for name in "${!profiles[@]}"; do
      echo "checking for profile in window name: $wm_name"
      if echo "$wm_name" | grep -F "[$name]"; then
        color="0x${profiles[$name]:1}"

        echo "found profile $name for node $node_id: $color"
        chwb -c "$color" $node_id
        break
      fi
    done
    echo
done
