# vim:ft=kitty
## name: Light Owl
## author: Sarah Drasner (theme), adapted for kitty
## upstream: https://github.com/sdras/night-owl-vscode-theme
## license: MIT

foreground                      #403f53
background                      #FBFBFB
selection_foreground            none
selection_background            #E0E0E0


#: Cursor colors
cursor                          #90A7B2
cursor_text_color               background


#: The basic 16 colors

#: black
color0 #403f53
color8 #989fb1

#: red
color1 #de3d3b
color9 #de3d3b

#: green
color2 #08916a
color10 #08916a

#: yellow
color3 #daaa01
color11 #e0af02

#: blue
color4 #288ed7
color12 #288ed7

#: magenta
color5 #d6438a
color13 #d6438a

#: cyan
color6 #2aa298
color14 #2aa298

#: white
color7 #f0f0f0
color15 #fafafa
