#!/bin/zsh
#export BAR_WIDTH="$(($(xrandr --query |awk -F '[ x+]' '/\<connected\>/{print $4}')-36))"

if pgrep -u $UID -x polybar >/dev/null;
then 
  # Polybar already running, send reload command
  polybar-msg cmd reload
else
  nohup polybar -c "$DOTFILES/polybar/config" bottom &> /dev/null &
fi
