#!/bin/zsh
export BAR_WIDTH="$(($(xrandr --query |awk -F '[ x+]' '/\<connected\>/{print $4}')-36))"

if pgrep -u $UID -x polybar >/dev/null;
then 
  # Polybar already running, send restart command
  polybar-msg cmd restart
else
  # Polybar not running, start it
  nohup polybar -c "$DOTFILES/polybar/config" bottom &> /dev/null &
fi
