#!/bin/zsh
# Terminate already running polybar instances
killall -q polybar

export BAR_WIDTH="$(($(xrandr --query |awk -F '[ x+]' '/\<connected\>/{print $4}')-36))"

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -c "$DOTFILES/polybar/config" bottom &
