#!/bin/zsh
function  launch {
  $DOTFILES/polybar/launch &
}

function launch_and_watch_xrandr_changes {
  launch

  xrandr-notify | while read -r batch; do
    echo "display properties changed, re-launching polybar"
    launch
  done
}

launch_and_watch_xrandr_changes &
