export DOTFILES=$HOME/dotfiles

if [ "$ZSH_PROFILING" = 1 ];
then
  zmodload zsh/zprof
fi

export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000000
export SAVEHIST=10000000

setopt BANG_HIST                   # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY            # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY          # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY               # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST      # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS            # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS        # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS           # Do not display a line previously found.
setopt HIST_IGNORE_SPACE           # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS           # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS          # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY                 # Don't execute immediately upon history expansion.
setopt HIST_BEEP                   # Beep when accessing nonexistent history.
setopt MENU_COMPLETE               # select first menu option automatically
setopt NO_NOMATCH                  # stop zsh from catching ^ chars.
setopt INTERACTIVE_COMMENTS        # allow comments in interactive shells

zstyle ":completion:*" menu select # Higlight item in completion menu

source ~/.zinit/bin/zinit.zsh
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Make sure to use double quotes
zinit for \
  load       "junegunn/fzf-bin"

source $DOTFILES/init.zsh
for f in $DOTFILES/**/init.zsh; do 
	source "$f"
done

for f in $DOTFILES/**/aliases.zsh; do 
	source "$f"
done

# Cycle through history based on characters already typed on the line
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Enter command mode with jj
bindkey 'jj' vi-cmd-mode

zinit wait lucid light-mode for \
  atload"_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
    zsh-users/zsh-completions \
  atinit"zicompinit; zicdreplay" \
    Aloxaf/fzf-tab

for plug in "extract" "thefuck"; do
  zinit snippet OMZ::plugins/$plug/$plug.plugin.zsh
done


if [ "$ZSH_PROFILING" = 1 ];
then
  zprof
fi
