if [ "$ZSH_PROFILING" = 1 ];
then
  zmodload zsh/zprof
fi
# If you come from bash you might have to change your $PATH.
#
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export DOTFILES=$HOME/dotfiles

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

plugins=(
  extract
  vi-mode
  history-substring-search
)

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


export DOTFILES_HOME="$HOME/dotfiles"
source $DOTFILES_HOME/init.zsh
for f in $DOTFILES_HOME/**/init.zsh; do 
	source "$f"
done

source $ZSH/oh-my-zsh.sh

for f in $DOTFILES_HOME/**/aliases.zsh; do 
	source "$f"
done

bindkey 'jj' vi-cmd-mode

if [ "$ZSH_PROFILING" = 1 ];
then
  zprof
fi
